### ISSUE TITLE
Console Navigation isn't working

### ISSUE THREAD

**Issue by tomfrenzel** [deinsoftware/toolbox#12]
# Prerequisites

- [*] I am running the latest version
- [*] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed

## Expected Behavior

When executing a command such as `cd C:\Windows\` the Shell terminal should navigate to the given URL.

## Current Behavior

The Terminal doesn't navigate.

## Failure Information (for bugs)

It doesn't show an Error message when executing the command

### Steps to Reproduce

1. Making sure that the Sample Script works.
1. changed Line 175 from
`_shell.Term("java -version 2>&1", Output.Internal);`
to
`_shell.Term(@"cd C:/Daten/", Output.Internal);`
`_shell.Term("dir", Output.Internal);`
1. Debug the Program -> outputs content of Debug Folder instead of C:/Windows/

### Context

- ToolBox Version: Latest
- Operating System: Windows 10 Pro
I tried multiple versions of execution the navigation such as:
 `_shell.Term(@"cd C:/Daten/", Output.Internal);`
`_shell.Term("cd C:\\Daten\\", Output.Internal);`
`_shell.Term(@"cd C:\Daten\", Output.Internal);`

**Comment by equiman** [comment]
I already tested and works, but `cd` command only change directory and have no output.
`_sell.term` have no memory between calls, that's what you need to run all commands in this session.

On [Term](https://github.com/deinsoftware/toolbox#term) documentation you can see how to run a command in specific path.

```bash
_shell.Term(command, Output.Internal, path);    //Path parameter define a path where the command needs to be executed
```

Also take a look of `path.Combine` in [path](https://github.com/deinsoftware/toolbox#paths) documentation. It is very useful.

Example:
`_shell.Term("npm i -f", Output.External, path.Combine("D:/Daten", "InsideFolder"));`

It will be run `npm i -f` inside `D:/Daten/InsideFolder`

Let me know if that explanation is enough to close this issue.
