### ISSUE TITLE
Async commands

### ISSUE THREAD

**Issue by MathieuDR** [deinsoftware/toolbox#13]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [YES] I am running the latest version
- [YES] I checked the documentation and found no answer
- [YES] I checked to make sure that this issue has not already been filed

Hello

I have a question about multi threading and opening new console processes so the 'main process' doesn't hang.

I need to run multiple OpenSCAD commands, which takes a long time. Hence I want to open a lot of console applications to run the commands async.

Is this possible with the toolbox and if so, could someone steer me in the right direction?

I've tried the following as a prototype

```csharp
     private ShellConfigurator GetShellConfigurator() {
            var notificationSystem = NotificationSystem.Default;
            IBridgeSystem bridgeSystem = null;
            switch (OS.GetCurrent())
            {
                case "win":
                    bridgeSystem = BridgeSystem.Bat;
                    break;
                case "mac":
                case "gnu":
                    bridgeSystem = BridgeSystem.Bash;
                    break;
            }
            return new ShellConfigurator(bridgeSystem, notificationSystem);
        }

        private void SendCommandstring openSCADLocation) {
            Parallel.Invoke(() => {
                var shell = GetShellConfigurator();
                Console.WriteLine("In Parallel");
                Response result = shell.Term(openSCADLocation);
                
            });
            Console.WriteLine("Want to continue running, so I can invoke way more");
            var oriShell = GetShellConfigurator();
            oriShell.Term("dotnet --ver");


            //Response result = _shell.Term(openSCADLocation);
        }
```

I've also tried to use AsyncEx where I used the [Async Context main ](https://github.com/StephenCleary/AsyncEx/blob/master/doc/AsyncContext.md) method and then run tasks as follow

```csharp
public async override Task DoAsync() {
            var firstTask = SendCommand("b", "c", Configuration.OpenSCADLocation);
            await SendCommand("b", "c", Configuration.OpenSCADLocation);
            await firstTask;
            return null;
        }

        private ShellConfigurator GetShellConfigurator() {
            var notificationSystem = NotificationSystem.Default;
            IBridgeSystem bridgeSystem = null;
            switch (OS.GetCurrent())
            {
                case "win":
                    bridgeSystem = BridgeSystem.Bat;
                    break;
                case "mac":
                case "gnu":
                    bridgeSystem = BridgeSystem.Bash;
                    break;
            }
            return new ShellConfigurator(bridgeSystem, notificationSystem);
        }

        private async Task SendCommand(string openSCADLocation) {           
            var oriShell = GetShellConfigurator();
            oriShell.Term(openSCADLocation);
        }
```

plus the [native support](https://stackoverflow.com/questions/38114553/are-async-console-applications-supported-in-net-core) of async methods. This also uses the code from above.

```csharp
     public static async Task Main(string[] args) { } 
```

**Comment by equiman** [comment]
Actually ToolBox uses ProcessStartInfo to process commands but it's not prepared to process multiple request.

Maybe you can use an approach like this to solve your problem:
https://stackoverflow.com/questions/10788982/is-there-any-async-equivalent-of-process-start 

Hope it can help!

Or if you want, can add this feature on ToolBox. This is the file where I used ProcessStartInfo.
[ToolBox/Bridge/ShellConfigurator.cs](https://github.com/deinsoftware/toolbox/blob/master/ToolBox/Bridge/ShellConfigurator.cs) on Term method.
