### ISSUE TITLE
Unable to install version 1.6.2

### ISSUE THREAD

**Issue by mcopjan** [deinsoftware/toolbox#15]
Restoring packages for .NETCoreApp,Version=v3.1...
  GET https://api.nuget.org/v3-flatcontainer/dein.toolbox/index.json
  OK https://api.nuget.org/v3-flatcontainer/dein.toolbox/index.json 153ms
  GET https://api.nuget.org/v3-flatcontainer/dein.toolbox/1.6.2/dein.toolbox.1.6.2.nupkg
  OK https://api.nuget.org/v3-flatcontainer/dein.toolbox/1.6.2/dein.toolbox.1.6.2.nupkg 567ms
Resolving conflicts for .NETCoreApp,Version=v3.1...
Acquiring lock for the installation of dein.ToolBox 1.6.2
Acquired lock for the installation of dein.ToolBox 1.6.2
Installing dein.ToolBox 1.6.2.
Access to the path '/Users/martinco/.nuget/packages/dein.toolbox/1.6.2/contentFiles/any/any' is denied.

**Comment by equiman** [comment]
I'm looking at what happens, maybe it's something related to 3.1 version or the automatic creations NuGet package with GitHub Actions. 

Please use 1.5.4 versions until I found what happened.

**Comment by equiman** [comment]
@mcopjan I have release version 1.6.3 and works locally.

Could you please test install it and tell me if it works?

**Comment by equiman** [comment]
I have tested it on other projects and works.
