### ISSUE TITLE
Just want to say...

### ISSUE THREAD

**Issue by mcopjan** [deinsoftware/toolbox#17]
hi @equiman, I just want to thank you for this project. It helped me to implement command bridge for my API which I am using on OSX as well as WIN. 
One thing I would like to suggest as an improvement (or maybe there is another way how to do it and I am just not aware of it)...

Regarding the Term() in ToolBox.Bridge.ShellConfigurator, sometimes I want to fire and forget a command so I would like to omit calling process.WaitForExit() (special cases such as starting Android Virtual Device)

For example on OSX I am executing "{MyCommand} & disown" which will run it as a background process and do not wait for process to return (in my case it would be hanging indefinitely). On Windows I did not find any other way than omit calling process.WaitForExit(). Is this something you would consider to add as an optional parameter?
```
public Response Term(string command, bool waitForExit = true, Output? output = Output.Hidden, string dir = "")
{
...
if(!waitForExit) return;
process.WaitForExit();
...
}
```

**Comment by equiman** [comment]
HI @mcopjan you welcome.

I'm never used `& disown` before. I think that I can implement what you say. But I need to test something before. 

Could you please make a test adding this ` 2>&1` at the end of your command? works?

Example:
`command & disown 2>&1`

**Comment by mcopjan** [comment]
Hi @equiman, I have tried the suggested example with the same result, process is executed, but because it is a long running process it will never terminate, so my app is hanging on Term().

**Comment by equiman** [comment]
Okey. I'll try to Implement your solution this weekend.

Thanks!

**Comment by mcopjan** [comment]
@equiman actuallyI manage to achieve what I needed by  
```
Task.Run(() => { Shell.Term(command); });
```

so no code change needed, thanks for your support and keep it up!
