### ISSUE TITLE
Problem sending multiple commands with space

### ISSUE THREAD

**Issue by reynaldots** [deinsoftware/toolbox#18]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Expected Behavior

That in bash all the command sent out will be the same as shown below:

`
cd /User/spppppppppppp/_hrm && ionic cordova resources ios && ionic cordova plugin remove cordova-plugin-facebook4 --variable APP_ID='x' --variable APP_NAME='x' && ionic cordova plugin add cordova-plugin-facebook4 --variable APP_ID='999999999999' --variable APP_NAME='App xx yyyyyy' && ionic cordova plugin remove cordova-plugin-googleplus --save --variable WEB_APPLICATION_CLIENT_ID='x' && rm -R /Users/pppppppppppppppppp/cordova-plugin-googleplus && ionic cordova plugin add cordova-plugin-googleplus --save --variable WEB_APPLICATION_CLIENT_ID='00000000000-yyyyyyyyyyyyy.apps.googleusercontent.com' --variable REVERSED_CLIENT_ID='com.googleusercontent.apps.xxxxxxxxxxxxxxxxxxxxxxxx'
`

## Current Behavior

The code below is sent at the terminal:

`
cd de; cd /Users/spppppppppppp/_hrm && ionic cordova resources ios && ionic cordova plugin remove cordova-plugin-facebook4 --variable APP_ID=x --variable APP_NAME=x && ionic cordova plugin add cordova-plugin-facebook4 --variable APP_ID=999999999999 --variable APP_NAME=App
MacOsPC:~ uuuuuuuu$ cd de; cd /Users/spppppppppppp/_hrm && ionic cordova resources ios && ionic cordova plugin remove cordova-plugin-facebook4 --variable APP_ID=x --variable APP_NAME=x && ionic cordova plugin add cordova-plugin-facebook4 --variable APP_ID=999999999999 --variable APP_NAME=App
`

I already tried to change the ' for " but there was no difference.
I switched to ` and the result was even worse.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Use the code given below.

`
List<string> cmds = new List<string>();
cmds.Add("cd /Users/xxxxxx");/* any folder*/
cmds.Add(string.Format(@"ionic cordova plugin add cordova-plugin-facebook4 --variable APP_ID=""{0}"" --variable APP_NAME=""{1}""", "99999999", "App Test iOS"));
RunCommandsMacOs(cmds); /* Reported below*/
`

2. Result:

`
MacOsPC:~ uuuuu$ cd Test; cd /Users/xxxxxx && ionic cordova plugin add cordova-plugin-facebook4 --variable APP_ID=99999999 --variable APP_NAME=App
-bash: cd: Test: No such file or directory
`

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

- ToolBox Version: 1.7.0
- Operating System: MacOS Mojave 10.14.4

- Code I use to send commands:

`
static void RunCommandsMacOs(List<string> cmds, string workingDirectory = "")
        {
            INotificationSystem _notificationSystem = NotificationSystem.Default;
            IBridgeSystem _bridgeSystem = BridgeSystem.Bash;
            ShellConfigurator _shell = new ShellConfigurator(_bridgeSystem, _notificationSystem);
            string strFinal = $"cd " + workingDirectory + " && " + String.Join(" && ", cmds);
            strFinal = strFinal.Replace("\"", "'");
            Response result = _shell.Term(strFinal, Output.External);
            Console.WriteLine(result.code.ToString());
            if (result.code == 0)
            {
                Console.WriteLine("Sucesso!");
            }
            else
            {
                Console.WriteLine("Erro Script iOS!");
                Console.WriteLine(result.stderr);
            }
        }
`

**Comment by equiman** [comment]
I'll recommend you read the documentation again. 

[Term](https://github.com/deinsoftware/toolbox#term) has a third parameter where you can define the path where the command will be executed and also [Path](https://github.com/deinsoftware/toolbox#paths) has a `Combine` method to define the path according to the OS. 

Also, remember to instantiate the interfaces on the class level and not inside the method. See [Shell](https://github.com/deinsoftware/toolbox#shell) documentation, 

Your code:
```csharp
        static void RunCommandsMacOs(List<string> cmds, string workingDirectory = "")
        {
            INotificationSystem _notificationSystem = NotificationSystem.Default; 
            IBridgeSystem _bridgeSystem = BridgeSystem.Bash; 
            ShellConfigurator _shell = new ShellConfigurator(_bridgeSystem, _notificationSystem); 

            string strFinal = $"cd " + workingDirectory + " && " + String.Join(" && ", cmds);

            strFinal = strFinal.Replace("\"", "'");
            Response result = _shell.Term(strFinal, Output.External);
            Console.WriteLine(result.code.ToString());
            if (result.code == 0) {
                Console.WriteLine("Success!");
            } else {
                Console.WriteLine("Erro Script iOS!"); Console.WriteLine(result.stderr);
            }
        }
```

Try again with something like this:

```csharp
        static void RunCommandsMacOs(List<string> cmds, string workingDirectory = "")
        {
            string strPath = _path.Combine(workingDirectory);
            string strFinal = String.Join(" && ", cmds);

            Response result = _shell.Term(strFinal, Output.External, strPath);
            
            Console.WriteLine(result.code.ToString());
            if (result.code == 0) {
                Console.WriteLine("Success!");
            } else {
                Console.WriteLine("Erro Script iOS!"); Console.WriteLine(result.stderr);
            }
        }
```

Also, take care of using multiple commands and conditional processing symbols (& or && it's different). The result is a responsibility from the command line and not of the ToolBox library. I would recommend you to run each code separately because you can deal with each response in isolation.

Hope it helps, tell me if it works.

**Comment by reynaldots** [comment]
I believe that I was not clear about the problem that is occurring.

Running command by command will not change anything about the reported problem.

Informing the path where I want to execute the command will also not change anything.

The main problem is related to sending a command with double quotes and it appears in the terminal completely broken.

If I send a command that contains the phrase "test app" for example through the MacOs terminal it works. But not sending through ToolBox.

I presented the example of how to simulate the problem and I believe that, perhaps due to lack of time, I believe that you cannot test.

If possible, please test the example I presented and then the problem will be presented.

**Comment by equiman** [comment]
I put your example in `Sample` project and it's launching the command correctly, but I see the `cmd.sh` it's removing the quotes character.

<img width="1680" alt="Screen Shot 2020-11-28 at 12 33 41" src="https://user-images.githubusercontent.com/933393/100522078-2b763080-3176-11eb-929f-9fdcfeb1c7c6.png">

<img width="585" alt="Screen Shot 2020-11-28 at 12 32 03" src="https://user-images.githubusercontent.com/933393/100522088-4648a500-3176-11eb-8162-2882a8862566.png">

What version of .Net are you using?

I'll try to take a lot later, or in the next week.

**Comment by reynaldots** [comment]
That's right! That is the problem.

cmd.sh it's removing the quotes character.

If I copy and paste the same 'text' directly into cmd.sh it works.

Something between the toolbox and cmd.sh is removing the quotes character.

I'm using dotnet core 3.1.402

I am in no hurry so when you have availability and can check I will be very grateful.

Sorry for any translation error, I'm Brazilian and I'm using Google translator

**Comment by equiman** [comment]
I've investigated a little and found it's not the shell. I've echoed the received parameters and called directly from the terminal and work as expected.

![Screen Shot 2020-12-01 at 17 38 52](https://user-images.githubusercontent.com/933393/100805288-66899580-33fc-11eb-9890-93a71bb32a69.png)

Even with spaces.

![Screen Shot 2020-12-01 at 17 43 43](https://user-images.githubusercontent.com/933393/100805630-f8919e00-33fc-11eb-8ba6-6177638a8fdc.png)

Maybe it's the .Net core but I need more time to debug what it's happening.

**Comment by equiman** [comment]
It was a problem with `ProcessStartInfo` `Argument` which was changed to `ArgumentList`. Fix and tested on Mac and Windows. 

![Screen Shot 2020-12-02 at 0 29 18](https://user-images.githubusercontent.com/933393/100832855-b2f1c700-3436-11eb-96dc-dbc541cd9ad8.png)

![Screen Shot 2020-12-02 at 0 36 59](https://user-images.githubusercontent.com/933393/100832868-b5542100-3436-11eb-8238-6dec61b7d261.png)

Please test with the 1.7.1 version and let me know if works.

**Comment by reynaldots** [comment]
Yes, it worked !!!
Thank you! =D

**Comment by equiman** [comment]
Your welcome. Thanks for reporting that!
