### ISSUE TITLE
Use Text.Json instead of Newtonsoft?

### ISSUE THREAD

**Issue by Simonl9l** [deinsoftware/toolbox#20]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X ] I am running the latest version
- [ X] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed

## Expected Behavior

Use `System.Text.Json`  to remove the Newtonsoft dependency ?

## Current Behavior

Has Newtonsoft dependency!

### Context

DotNet 6 is here, and `System.Text.Json` is now well supported. doing this eliminates a package dependency!

**Comment by equiman** [comment]
@Simonl9l thanks for your report.

The `Newtonsoft` dependency was removed. Version 1.9.0 was published.
