### ISSUE TITLE
SonarQube link in readme returns 404

### ISSUE THREAD

**Issue by JohannesMP** [deinsoftware/toolbox#21]
![image](https://user-images.githubusercontent.com/662874/160681052-c4e6f630-b464-498f-b61a-c154417fbe18.png)

The 'SonarQube' link in the [**Built With** section of the readme](https://github.com/deinsoftware/toolbox#built-with), points to https://sonarcloud.io/dashboard/index/dein:toolbox which currently results in a 404:
![image](https://user-images.githubusercontent.com/662874/160680756-36386dfe-3a62-4abd-b4dd-6e7c87c49386.png)

**Comment by equiman** [comment]
Fixed, thanks for your report
