### ISSUE TITLE
Target framework - netcoreapp2.0

### ISSUE THREAD

**Issue by xfoggi** [deinsoftware/toolbox#4]
I tried installing the nugget into my core 2.0 project and it was successfully installed. But I was not able to reference it inside the project - when I tried the Colorify from the sample, I failed to install with regards to incorrect target framework (required 2.1). So I changed the target framework in my project and it started to work without issue.

So you might consider setting the req. version to >2.1 same as you have it for Colorify nugget :)

**Comment by equiman** [comment]
Hi @xfoggi I'm trying understand where did you see this version 2.0 because I already updated to 2.1 on 1.4.3 version: https://github.com/deinsoftware/toolbox/commit/e0e6bbca8a1606f52abbebb2079fd175d399b331

It's something on documentation?

**Comment by xfoggi** [comment]
Hey @equiman, failed to spot the notification. I was installing this package via Nuget package manager - and it allowed me to install it in 2.0 project, which then was unable to reference, but was installed. Maybe something was wrong inside my project, just wanted to let you know this happened.

**Comment by equiman** [comment]
@xfoggi I'll be a check on nugget package configuration. Maybe I'm missing something. 

Thanks!

**Comment by xfoggi** [comment]
There's really no way how to write someone a message and ask for some questions - if you don't mind, I would use this issue :) 

My current use case - I'm working on Mobile management tool, that is using Appium to run automation on mobile devices. For running Appium on Mac OS (also on Linux and Windows) in the background, I'm trying to use your tool - so I don't have to reimplement the wheel and configure running on each system. With the mac, I have to use osascript to run the command in a separate terminal. This terminal is then identified by a mobile device ID, which is some kind of unique GUID. So I have used the Shell.Term with the External option and this keeps the Appium running in a new terminal window. 

This is all very great and lovely until I need to close the Appium and the terminal window. If I send kill event to appium process, it leaves the terminal window opened. Soo .. after a while you have quite a lot of opened terminals doing nothing. To handle this, I used the osascript with command _tell application "Terminal" to close (every window whose name contains "$id")_. But this is something I need to handle manually outside your implementation. Maybe I have overlooked something in your code, but I couldn't find it.

So my question, do you think there is some way how to handle such behavior? Running a process in the background and then stopping it via an osascript close terminal command with your current implementation? Or is there something I'm missing and should do it otherwise?

Thanks!

**Comment by equiman** [comment]
Well I have same issue and don't found an easy way to solve it. That's why I create different outputs.

```csharp
_shell.Term(command);                           //Run a command in hidden mode
_shell.Term(command, Output.Hidden);            //Run a command in hidden mode
_shell.Term(command, Output.Internal);          //Run a command in internal mode, showing his results in same terminal with INotificationSystem implementation
_shell.Term(command, Output.External);          //Run a command in a new terminal window
_shell.Term(command, Output.Internal, path);    //Path parameter define a path when the command needs to be executed
```
External mode create a new window to run the command but lose the control inside .Net core because it's running on a bat/bash command. Maybe you can try with the other options, because you can preserve the link with .Net. 

Something like Hidden running on an Async process?

I'll try think a solution because I'm creating a new window to run a web server but i'm closing it manually. It will be good idea can close it from main program.

**Comment by xfoggi** [comment]
So far, I ended up with a close script, similar to your cmd scripts ... it's not perfect, but it's doing what I need to.
```
#!/bin/bash
id="$1";

osascript <<EOF
    tell application "Terminal" to close (every window whose name contains "$id")
EOF

exit 0
```

I will try to experiment a bit with those other Output options to see if I can manage to run it in the separate async thread. Will give you an update of how it goes :)

**Comment by equiman** [comment]
Excellent, how do you know/get the terminal id?

**Comment by xfoggi** [comment]
it actually searches for the string in terminal name :D in my case every appium process is run with unique mobile ID, so there can't be at a time other terminal opened with the same name. (The terminal name contains the running process with its parameters).
It's definitely not perfect and reusable... I would love to find out the pid of the opened terminal, it should be possible, but could not find the solution for it yet.

**Comment by equiman** [comment]
I added support for .Net Core 2.0 and 2.1 inside the same NuGet package. Maybe can it help avoid the error.  I will close this issue, but feel free comment if you have more questions.
