### ISSUE TITLE
cmd.sh: No such file or directory          

### ISSUE THREAD

**Issue by mcopjan** [deinsoftware/toolbox#5]
Version 1.4.4
macOs Mojave 10.14.1
Net Core 2.1.0

I tried to take your Sample project and run it but when cmd.sh is being searched for it is looked for at a wrong location, so in output I get is

sh: /Users/admin/Projects/TestPowerShell/TestPowerShell/cmd.sh: No such file or directory

My cmd.sh is located at /Users/admin/Projects/TestPowerShell/TestPowerShell/bin/Debug/netcoreapp2.1/cmd.sh. Is there a way to change the location cmd.sh is being searched for?

**Comment by mcopjan** [comment]
I have tried
`_shell.Term("appium --v", Output.External, "/Users/admin/Projects/TestPowerShell/TestPowerShell/bin/Debug/netcoreapp2.1/");`

as well, with the same result unfortunately :/

**Comment by equiman** [comment]
If you want to run this Sample project with `dotnet run` need copy manually this files this files in the root of your project:
https://github.com/deinsoftware/toolbox/blob/master/ToolBox/cmd.bat
https://github.com/deinsoftware/toolbox/blob/master/ToolBox/cmd.sh

Remember set execution permissions to this file on macOS:
`chmod +x cmd.sh`

But when you publish the project `dotnet publish Sample.csproj -o ./Library/mac -c release -r osx.10.12-x64`, both files will be automatically copied to root publish folder and set execution permissions to bash file.

Hope it help, please let me know if it solves the problem.

DP: I already update the packages version. Please pull those changes.

**Comment by equiman** [comment]
I added this bash/bat files directly on the Sample project to avoid this confusion. 
Please pull changes.

**Comment by mcopjan** [comment]
Hi @equiman, thanks a lot for your quick reply. I could see that both cmd.bat and cmd.sh were copied in the root of my project so I attached Toolbox as a project to debug my problem and here are my findings together with a code to reproduce:

```
class Program
    {
        public static INotificationSystem _notificationSystem { get; set; }
        public static IBridgeSystem _bridgeSystem { get; set; }
        public static ShellConfigurator _shell { get; set; }
        static void Main(string[] args)
        {
            _notificationSystem = NotificationSystem.Default;
            switch (OS.GetCurrent())
            {
                case "win":
                    _bridgeSystem = BridgeSystem.Bat;
                    break;
                case "mac":
                case "gnu":
                    _bridgeSystem = BridgeSystem.Bash;
                    break;
            }
            _shell = new ShellConfigurator(_bridgeSystem);
            
            _shell.Term("ipconfig", Output.External);
        }
    }
```

When I run this the following command is being executed 

cmd.exe /c "c:\users\marti\documents\visual studio 2017\Projects\ConsoleApp3\bin\Debug\netcoreapp2.1/cmd.bat "ipconfig""

because of the white spaces in the path I get 

"'c:\users\marti\documents\visual' is not recognized as an internal or external command,
operable program or batch file."

So I have played around a bit and the following changes in CommandConstructor() works for me 
```
        public string CommandConstructor(string command, Output? output = Output.Hidden, string dir = "")
        {
            if (!String.IsNullOrEmpty(dir))
            {
                dir = $" \"{dir}\"";
            }
            if (output == Output.External)
            {
                command = $"\"{Directory.GetCurrentDirectory()}/cmd.bat\" \"{command}\"{dir}";
            }
            command = $"/c \"{command}\"";
            return command;
        }
```
notice extra double quotes in \"{Directory.GetCurrentDirectory()}/cmd.bat\"

If you are happy I will look into BridgeSystemBash as it may require changes as well and then send you a PR?

**Comment by equiman** [comment]
Of course. Please make it as PR.
Please change it on `BridgeSystemBash.cs` and `BridgeSystemBat.cs`

 Thanks!

**Comment by mcopjan** [comment]
HI @equiman, I have the code ready. I have tried to push my changes into a new branch and then create PR for merge into master but I am failing on authentication

git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree push -v --tags origin refs/heads/master:refs/heads/extrenalExecutionFix 
Pushing to https://github.com/deinsoftware/toolbox.git
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/deinsoftware/toolbox.git/'
Pushing to https://github.com/deinsoftware/toolbox.git
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/deinsoftware/toolbox.git/'
Pushing to https://github.com/deinsoftware/toolbox.git
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/deinsoftware/toolbox.git/'
Pushing to https://github.com/deinsoftware/toolbox.git
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/deinsoftware/toolbox.git/'
Completed with errors, see above

Is there anything you have to allow from your side? Do I need a permission to create a new branch?

**Comment by equiman** [comment]
As far I know... you don't need my permissions. 
But if you are trying commit those changes directly on my repo it will fail.

Just create a fork, push changes on it and then make a PR from fork to my repo.

https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

**Comment by mcopjan** [comment]
@equiman Thanks, all good now. I could not push my changes because of old credentials stored in KeyChain. Please have a look at the PR I submitted when you have time.

**Comment by equiman** [comment]
@mcopjan I'm updating to netcore 2.2. I will add the fixes by myself. Thanks!

**Comment by mcopjan** [comment]
@equiman Ok great, back to your comment about Directory.GetCurrentDirectory(), yes it did not work on Mac so I had find Assembly execution path via Reflection
