### ISSUE TITLE
Shell with Path on Mac not working

### ISSUE THREAD

**Issue by SmartieCodes** [deinsoftware/toolbox#7]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior

I would like to run npm run build inside a particular directory.
`Response result = _shell.Term("npm run build", ToolBox.Bridge.Output.Internal, sourcePath);`

## Current Behavior

This is working perfectly on windows, but on a mac it does nothing, no error, no anything? I have changed the line to something very simple:
`Response result = _shell.Term("dotnet --version", ToolBox.Bridge.Output.Internal);`
And that ouputs the version number on a mac okay, but if I also pass in a path to run it under, it goes back to doing nothing at all. I have checked the path passed in on a mac and it is correct.

## Objective
We are currently using the following on our windows program to open a new terminal, wait for the build to finish, that it will continue to do the next step. We would like this to work on a mac as well, so I was hoping your library would enable us to do this:

```
using (var cmd = new Process())
{
    cmd.StartInfo.WorkingDirectory = sourcePath;
    cmd.StartInfo.FileName = "cmd.exe";
    cmd.StartInfo.Arguments = "/C npm run build";
    cmd.Start();

    cmd.WaitForExit();
}
```

Thanks

**Comment by equiman** [comment]
Hi @LeahPike i'm actually using it to run a lot of commands in both OS (Win and Mac), you can see different commands and usage on this links:
https://github.com/deinsoftware/hardhat/tree/master/HardHat/controller

One of this files have gulp and npm commands: https://github.com/deinsoftware/hardhat/blob/master/HardHat/controller/Gulp.cs

And are working fine. I think, your issue can be something related directly to run the command on terminal. This library work as a bridge between the program and the console, but needs the console do the task correctly.

Are you try to run this command manually on your console?
What is the result?

**Comment by equiman** [comment]
Hi @LeahPike did you solve the problem?

Maybe this post can explain better how it works.

https://dev.to/deinsoftware/run-a-command-in-external-terminal-with-net-core-d4l

**Comment by SmartieCodes** [comment]
Thank you for the replies, so embarrassingly the mac path was incorrect, it needed forward slashes instead of backslashes. ( So much wasted time XD )

I'm going to have a read through of the links you've given, and just check I've done it all correctly, but it's successfully running the command internally now.

Thanks again!

Windows
> "sourcePath": "C:\\GitHub\\activ\\src\\clients\\activ-id"

Mac
> "sourcePath": "/Users/Darren/github/activ/src/clients/activ-id"

**Comment by equiman** [comment]
No problem. You're welcome!
