### ISSUE TITLE
No colours coming through in terminal

### ISSUE THREAD

**Issue by kareem613** [deinsoftware/toolbox#8]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

## Expected Behavior

Term output doesn't respect colours.

## Current Behavior

Output doesn't show the colour.

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Execute a command that has colour output. 
ex. `_shell.Term("ls -la", Output.Internal);`

### Context

- ToolBox Version: latest master
- Operating System: ubuntu (WSL in windows)

### Failure Logs

none

**Comment by equiman** [comment]
Can you add an image, I can't understand what it means:  don't respect colors.

`Output.Internal` it's not an option for colors, If you want define colors in terminal need use Colorify: https://github.com/deinsoftware/colorify
