### ISSUE TITLE
Issue when including dein.toolbox in a dotnet tool

### ISSUE THREAD

**Issue by Illedan** [deinsoftware/toolbox#9]
# Prerequisites
I'm using dein.toolbox in a dotnet tool to open the terminal.
Usage can be viewed here:
https://github.com/Illedan/OpenRepo/blob/master/src/OpenRepo/Services/TerminalService.cs

## Expected Behavior
I'm expecting dein.toolbox's terminal to work in a published dotnet tool.

## Current Behavior
Works when running from `dotnet run` or from Visual Studio, but not from the published tool.
Also working when running it as `Hidden`.

## Failure Information (for bugs)
Silent failure, not logging anything as far as I can tell.

### Context
I think it occurs because of how dotnet tools are installed. As it appears in $HOME/.dotnet/tools as an exe file without cmd.bat / cmd.sh even though they are found inside the NuGet package: https://www.nuget.org/packages/OpenRepo/

- ToolBox Version: 1.5.3
- Operating System: Mac/ Windows

**Comment by equiman** [comment]
What version of .netCore are using?

**Comment by Illedan** [comment]
I'm using 3.0.
https://github.com/Illedan/OpenRepo/blob/master/src/OpenRepo/OpenRepo.csproj#L5
I had 2.3 earlier and it didn't work either.

**Comment by equiman** [comment]
I'll try update to .NetCore 3 this weekend and see whats happened

**Comment by equiman** [comment]
What version of NuGet Package manager are you using?

**Comment by equiman** [comment]
I have created a new version (only netCore 2.2 and 3.0 support): 
https://www.nuget.org/packages/dein.ToolBox/1.5.4

I already tested on Test project and Works.

**Comment by Illedan** [comment]
I updated to 1.5.4, but the behaviour is similar.
I create a local NuGet package and install my dotnet tool from it, which works initially as intended. But it stops working once I restart my mac. Works again if I reinstall my tool. (Configuration is saved cross installation and there is no extra work done on a new installation afaik)

I can try to create a minimal example as a testproject and add to this repo for you to reproduce.

**Comment by equiman** [comment]
mmm sounds that it's another problem and it's not related to the library.

**Comment by Illedan** [comment]
I think it's related to the library being used in a dotnet tool.

**Comment by equiman** [comment]
Try run the Sample project inside this repo.

**Comment by equiman** [comment]
Works Sample in your machine?

**Comment by Illedan** [comment]
Hi, sorry about my late reply, had some busy days.
Yes, the sample works when running from Visual studio. Or with dotnet run, but I also get this behaviour when running my project too. Problem occurs once published as a dotnet tool.

**Comment by equiman** [comment]
I added and testes Toolbox in console projects, but I had never use as `dotnet tool`. 

I'm reading documentation about the difference:
https://www.dotnetcurry.com/dotnet/1495/dotnet-core-global-tools

I think dein.Toolbox was made to use in console application. Maybe need some adjustment to be compatible with `dotnet tool`, but I don't have much free time this days.

Maybe I'll take a look in the future.

**Comment by equiman** [comment]
I have changed the Package construction with:
<developmentDependency>false</developmentDependency>

Could you please test if it solves the problem?
